import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const core = await readFile(new URL('src/core.js', root), 'utf8');
const app = await readFile(new URL('src/app.js', root), 'utf8');
const header = await readFile(new URL('src/metadata.txt', root), 'utf8');
const output = `${header}\n(() => {\n'use strict';\n${core}\n${app}\n})();\n`;
await mkdir(new URL('dist/', root), { recursive: true });
await writeFile(new URL('dist/torn-targetlist.user.js', root), output);
console.log(`Built ${fileURLToPath(new URL('dist/torn-targetlist.user.js', root))}`);
